// Code generated by gen-param.b from qtachart_functions.cpp
// This is the body of QTACFunctions::addIndicator()

  if (fname == QLatin1String ("SMA"))
  {
    obj = referencechart->addStudySMA( fname, (qint32) PARAM("Period"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("EMA"))
  {
    obj = referencechart->addStudyEMA( fname, (qint32) PARAM("Period"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("MACD"))
  {
    obj = referencechart->addStudyMACD( fname, (qint32) PARAM("Period"), PARAM("MACD color"), PARAM("Signal color") );
  }
  else if (fname == QLatin1String ("MFI"))
  {
    obj = referencechart->addStudyMFI( fname, (qint32) PARAM("Period"), (qint32) PARAM("High level"), (qint32) PARAM("Medium level"), (qint32) PARAM("Low level"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("ROC"))
  {
    obj = referencechart->addStudyROC( fname, (qint32) PARAM("Period"), (qint32) PARAM("Level"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("RSI"))
  {
    obj = referencechart->addStudyRSI( fname, (qint32) PARAM("Period"), (qint32) PARAM("High level"), (qint32) PARAM("Low level"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("Slow Stoch"))
  {
    obj = referencechart->addStudySlowStoch( fname, (qint32) PARAM("Period"), (qint32) PARAM("High level"), (qint32) PARAM("Medium level"), (qint32) PARAM("Low level"), PARAM("%K color"), PARAM("%D color") );
  }
  else if (fname == QLatin1String ("Fast Stoch"))
  {
    obj = referencechart->addStudyFastStoch( fname, (qint32) PARAM("Period"), (qint32) PARAM("High level"), (qint32) PARAM("Medium level"), (qint32) PARAM("Low level"), PARAM("%K color"), PARAM("%D color") );
  }
  else if (fname == QLatin1String ("W%R"))
  {
    obj = referencechart->addStudyW_percent_R( fname, (qint32) PARAM("Period"), (qint32) PARAM("High level"), (qint32) PARAM("Low level"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("Bollinger Bands"))
  {
    obj = referencechart->addStudyBollingerBands( fname, (qint32) PARAM("Period"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("Parabolic SAR"))
  {
    obj = referencechart->addStudyParabolicSAR( fname, PARAM("Color") );
  }
  else if (fname == QLatin1String ("ADX"))
  {
    obj = referencechart->addStudyADX( fname, (qint32) PARAM("Period"), (qint32) PARAM("Weak"), (qint32) PARAM("Strong"), (qint32) PARAM("Very strong"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("Aroon"))
  {
    obj = referencechart->addStudyAroon( fname, (qint32) PARAM("Period"), (qint32) PARAM("High level"), (qint32) PARAM("Medium level"), (qint32) PARAM("Low level"), PARAM("Up color"), PARAM("Down color") );
  }
  else if (fname == QLatin1String ("CCI"))
  {
    obj = referencechart->addStudyCCI( fname, (qint32) PARAM("Period"), (qint32) PARAM("High level"), (qint32) PARAM("Low level"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("STDDEV"))
  {
    obj = referencechart->addStudySTDDEV( fname, (qint32) PARAM("Period"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("Momentum"))
  {
    obj = referencechart->addStudyMomentum( fname, (qint32) PARAM("Period"), (qint32) PARAM("Level"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("DMI"))
  {
    obj = referencechart->addStudyDMI( fname, (qint32) PARAM("Period"), (qint32) PARAM("Weak"), (qint32) PARAM("Strong"), (qint32) PARAM("Very strong"), PARAM("Color") );
  }
  else if (fname == QLatin1String ("ATR"))
  {
    obj = referencechart->addStudyATR( fname, (qint32) PARAM("Period"), PARAM("Color") );
  }
