// Code generated by gen-param.b from qtachart_functions.cpp

static DynParamsDialog*
_paramDialogSMA(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("SMA"), bd.wparent);
  _addButton(bd, QStringLiteral("SMA"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 14);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogEMA(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("EMA"), bd.wparent);
  _addButton(bd, QStringLiteral("EMA"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 14);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogMACD(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("MACD"), bd.wparent);
  _addButton(bd, QStringLiteral("MACD"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 14);
  dlg->addParam(QStringLiteral("MACD color"), QStringLiteral("MACD color"),
                DPT_COLOR, qRgb(255,255,0));
  dlg->addParam(QStringLiteral("Signal color"), QStringLiteral("Signal color"),
                DPT_COLOR, qRgb(255,0,0));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogMFI(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("MFI"), bd.wparent);
  _addButton(bd, QStringLiteral("MFI"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 14);
  dlg->addParam(QStringLiteral("High level"), QStringLiteral("High level"),
                DPT_INT, 80);
  dlg->addParam(QStringLiteral("Medium level"), QStringLiteral("Medium level"),
                DPT_INT, 50);
  dlg->addParam(QStringLiteral("Low level"), QStringLiteral("Low level"),
                DPT_INT, 20);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogROC(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("ROC"), bd.wparent);
  _addButton(bd, QStringLiteral("ROC"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 10);
  dlg->addParam(QStringLiteral("Level"), QStringLiteral("Level"),
                DPT_INT, 0);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogRSI(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("RSI"), bd.wparent);
  _addButton(bd, QStringLiteral("RSI"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 14);
  dlg->addParam(QStringLiteral("High level"), QStringLiteral("High level"),
                DPT_INT, 70);
  dlg->addParam(QStringLiteral("Low level"), QStringLiteral("Low level"),
                DPT_INT, 30);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogSlowStoch(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("Slow Stoch"), bd.wparent);
  _addButton(bd, QStringLiteral("Slow Stoch"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 5);
  dlg->addParam(QStringLiteral("High level"), QStringLiteral("High level"),
                DPT_INT, 80);
  dlg->addParam(QStringLiteral("Medium level"), QStringLiteral("Medium level"),
                DPT_INT, 50);
  dlg->addParam(QStringLiteral("Low level"), QStringLiteral("Low level"),
                DPT_INT, 20);
  dlg->addParam(QStringLiteral("%K color"), QStringLiteral("%K color"),
                DPT_COLOR, qRgb(0,255,255));
  dlg->addParam(QStringLiteral("%D color"), QStringLiteral("%D color"),
                DPT_COLOR, qRgb(255,255,0));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogFastStoch(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("Fast Stoch"), bd.wparent);
  _addButton(bd, QStringLiteral("Fast Stoch"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 5);
  dlg->addParam(QStringLiteral("High level"), QStringLiteral("High level"),
                DPT_INT, 80);
  dlg->addParam(QStringLiteral("Medium level"), QStringLiteral("Medium level"),
                DPT_INT, 50);
  dlg->addParam(QStringLiteral("Low level"), QStringLiteral("Low level"),
                DPT_INT, 20);
  dlg->addParam(QStringLiteral("%K color"), QStringLiteral("%K color"),
                DPT_COLOR, qRgb(0,255,255));
  dlg->addParam(QStringLiteral("%D color"), QStringLiteral("%D color"),
                DPT_COLOR, qRgb(255,255,0));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogW_percent_R(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("W%R"), bd.wparent);
  _addButton(bd, QStringLiteral("W%R"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 14);
  dlg->addParam(QStringLiteral("High level"), QStringLiteral("High level"),
                DPT_INT, -20);
  dlg->addParam(QStringLiteral("Low level"), QStringLiteral("Low level"),
                DPT_INT, -80);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogBollingerBands(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("Bollinger Bands"), bd.wparent);
  _addButton(bd, QStringLiteral("Bollinger Bands"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 20);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(255,0,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogParabolicSAR(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("Parabolic SAR"), bd.wparent);
  _addButton(bd, QStringLiteral("Parabolic SAR"), dlg);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogADX(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("ADX"), bd.wparent);
  _addButton(bd, QStringLiteral("ADX"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 13);
  dlg->addParam(QStringLiteral("Weak"), QStringLiteral("Weak"),
                DPT_INT, 25);
  dlg->addParam(QStringLiteral("Strong"), QStringLiteral("Strong"),
                DPT_INT, 50);
  dlg->addParam(QStringLiteral("Very strong"), QStringLiteral("Very strong"),
                DPT_INT, 75);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogAroon(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("Aroon"), bd.wparent);
  _addButton(bd, QStringLiteral("Aroon"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 25);
  dlg->addParam(QStringLiteral("High level"), QStringLiteral("High level"),
                DPT_INT, 70);
  dlg->addParam(QStringLiteral("Medium level"), QStringLiteral("Medium level"),
                DPT_INT, 50);
  dlg->addParam(QStringLiteral("Low level"), QStringLiteral("Low level"),
                DPT_INT, 30);
  dlg->addParam(QStringLiteral("Up color"), QStringLiteral("Up color"),
                DPT_COLOR, qRgb(0,255,0));
  dlg->addParam(QStringLiteral("Down color"), QStringLiteral("Down color"),
                DPT_COLOR, qRgb(255,0,0));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogCCI(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("CCI"), bd.wparent);
  _addButton(bd, QStringLiteral("CCI"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 20);
  dlg->addParam(QStringLiteral("High level"), QStringLiteral("High level"),
                DPT_INT, 100);
  dlg->addParam(QStringLiteral("Low level"), QStringLiteral("Low level"),
                DPT_INT, -100);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogSTDDEV(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("STDDEV"), bd.wparent);
  _addButton(bd, QStringLiteral("STDDEV"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 10);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogMomentum(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("Momentum"), bd.wparent);
  _addButton(bd, QStringLiteral("Momentum"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 12);
  dlg->addParam(QStringLiteral("Level"), QStringLiteral("Level"),
                DPT_INT, 0);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogDMI(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("DMI"), bd.wparent);
  _addButton(bd, QStringLiteral("DMI"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 13);
  dlg->addParam(QStringLiteral("Weak"), QStringLiteral("Weak"),
                DPT_INT, 25);
  dlg->addParam(QStringLiteral("Strong"), QStringLiteral("Strong"),
                DPT_INT, 50);
  dlg->addParam(QStringLiteral("Very strong"), QStringLiteral("Very strong"),
                DPT_INT, 75);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

static DynParamsDialog*
_paramDialogATR(const ButtonInitData& bd)
{
  DynParamsDialog* dlg = new DynParamsDialog(QStringLiteral("ATR"), bd.wparent);
  _addButton(bd, QStringLiteral("ATR"), dlg);
  dlg->addParam(QStringLiteral("Period"), QStringLiteral("Period"),
                DPT_INT, 14);
  dlg->addParam(QStringLiteral("Color"), QStringLiteral("Color"),
                DPT_COLOR, qRgb(0,255,255));
  _connectPDialog(dlg, bd.parent);
  return dlg;
}

