// Code generated by gen-param.b from qtachart_functions.cpp

void MainWindow::addStudyItems()
{
    QAction* act;
    act = _studies->addAction( "SMA", this, SLOT(addStudy()) );
    act->setData( 0 );
    act = _studies->addAction( "EMA", this, SLOT(addStudy()) );
    act->setData( 1 );
    act = _studies->addAction( "MACD", this, SLOT(addStudy()) );
    act->setData( 2 );
    act = _studies->addAction( "MFI", this, SLOT(addStudy()) );
    act->setData( 3 );
    act = _studies->addAction( "ROC", this, SLOT(addStudy()) );
    act->setData( 4 );
    act = _studies->addAction( "RSI", this, SLOT(addStudy()) );
    act->setData( 5 );
    act = _studies->addAction( "Slow Stoch", this, SLOT(addStudy()) );
    act->setData( 6 );
    act = _studies->addAction( "Fast Stoch", this, SLOT(addStudy()) );
    act->setData( 7 );
    act = _studies->addAction( "W%R", this, SLOT(addStudy()) );
    act->setData( 8 );
    act = _studies->addAction( "Bollinger Bands", this, SLOT(addStudy()) );
    act->setData( 9 );
    act = _studies->addAction( "Parabolic SAR", this, SLOT(addStudy()) );
    act->setData( 10 );
    act = _studies->addAction( "ADX", this, SLOT(addStudy()) );
    act->setData( 11 );
    act = _studies->addAction( "Aroon", this, SLOT(addStudy()) );
    act->setData( 12 );
    act = _studies->addAction( "CCI", this, SLOT(addStudy()) );
    act->setData( 13 );
    act = _studies->addAction( "STDDEV", this, SLOT(addStudy()) );
    act->setData( 14 );
    act = _studies->addAction( "Momentum", this, SLOT(addStudy()) );
    act->setData( 15 );
    act = _studies->addAction( "DMI", this, SLOT(addStudy()) );
    act->setData( 16 );
    act = _studies->addAction( "ATR", this, SLOT(addStudy()) );
    act->setData( 17 );
    act = _studies->addAction( "Range", this, SLOT(addStudy()) );
    act->setData( 18 );
}
