// Code generated by gen-param.b from qtachart_functions.cpp
// This is the switch in MainWindow::addStudy().

        case 0:
            chart->addStudySMA( "SMA", 14, qRgb(0,255,255) );
            chart->goBack();
            break;
        case 2:
            chart->addStudyMACD( "MACD", 14, qRgb(255,255,0), qRgb(255,0,0) );
            chart->goBack();
            break;
